apiVersion: v2
name: uniproxy
description: Universal test proxy for dependency health monitoring
version: 0.2.0
appVersion: "0.7.0"
type: application
keywords:
  - dephealth
  - health-check
  - proxy
  - monitoring
  - prometheus
home: https://github.com/BigKAA/uniproxy
sources:
  - https://github.com/BigKAA/uniproxy
